process.env.JWT_SECRET = 'test-secret';

import { describe, it, expect, vi } from 'vitest';

// Mock the db connection so importing authService doesn't trigger better-sqlite3
vi.mock('../../db/connection.js', () => ({
  db: {},
  getDb: () => ({}),
  default: {},
}));

const {
  hashPassword,
  verifyPassword,
  generateToken,
  verifyToken,
} = await import('../authService.js');

import type { TokenPayload } from '../authService.js';

describe('authService', () => {
  describe('hashPassword / verifyPassword', () => {
    it('verifyPassword returns true for matching password', () => {
      const password = 'my-secure-password';
      const hash = hashPassword(password);

      expect(hash).not.toBe(password);
      expect(verifyPassword(password, hash)).toBe(true);
    });

    it('verifyPassword returns false for wrong password', () => {
      const hash = hashPassword('correct-password');
      expect(verifyPassword('wrong-password', hash)).toBe(false);
    });
  });

  describe('generateToken / verifyToken', () => {
    const user: TokenPayload = {
      id: 1,
      username: 'alice',
      role: 'admin',
    };

    it('verifyToken decodes a token generated by generateToken', () => {
      const token = generateToken(user);
      const decoded = verifyToken(token);

      expect(decoded.id).toBe(user.id);
      expect(decoded.username).toBe(user.username);
      expect(decoded.role).toBe(user.role);
    });

    it('verifyToken throws on an invalid token', () => {
      expect(() => verifyToken('invalid.token.value')).toThrow();
    });

    it('verifyToken throws on a tampered token', () => {
      const token = generateToken(user);
      const tampered = token.slice(0, -1) + (token.at(-1) === 'a' ? 'b' : 'a');
      expect(() => verifyToken(tampered)).toThrow();
    });
  });
});
